use_frameworks!

platform :ios, '8.0'

target 'GGZIntegrationDylibPodProject_Example' do
  pod 'GGZIntegrationDylibPodProject', :path => '../'

  target 'GGZIntegrationDylibPodProject_Tests' do
    inherit! :search_paths

    
  end
end
